### ISSUE TITLE
live website looks broken

### ISSUE THREAD

**Issue by sasha-astiadi** [ourworldventures/www_ourworld_tf#1]
https://ourverse.tf/
<img width="1440" alt="Screenshot 2022-10-25 at 14 18 40" src="https://user-images.githubusercontent.com/43240801/197771424-7b11844c-7ce4-475b-b004-beaa1014b6aa.png">

pages look broken, or is it just my laptop?
please take a look, i couldnt fix it @timurgordon @ehab-hassan

**Comment by sasha-astiadi** [comment]
https://github.com/ourworld-tsc/www_ourverse/issues/4

**Comment by ehab-hassan** [comment]
wrong repo fixed there
https://github.com/ourworld-tsc/www_ourverse/issues/4
