### ISSUE TITLE
Explore buttons not working

### ISSUE THREAD

**Issue by Ashishban** [ourworldventures/www_ourworld_tf#10]
URL - https://ourworld.tf/experiences/

Directed to - https://www.ourworld.tf%22https//ourverse.tf%22

<img width="907" alt="10" src="https://user-images.githubusercontent.com/91247662/220121993-112dbfe4-93f3-478b-ada5-8ece4934f2bd.png">

<img width="908" alt="11" src="https://user-images.githubusercontent.com/91247662/220124762-7406247e-7d32-4c97-a435-6b0662a3b90b.png">

<img width="525" alt="2" src="https://user-images.githubusercontent.com/91247662/220122905-ee75b13c-5322-4cd0-8a2d-2fbc0715a599.png">

**Comment by Ashishban** [comment]
Also, the image does not seem to be showing on my laptop for Sikana

**Comment by ehab-hassan** [comment]
fixed
