### ISSUE TITLE
fix mobile view

### ISSUE THREAD

**Issue by sasha-astiadi** [ourworldventures/www_ourworld_tf#15]
just margin lefr right on all pages

![Image](https://github.com/threefoldfoundation/www_ourworld_tf/assets/43240801/3a873dba-964e-466d-8b19-5430c9a479bc)
![Image](https://github.com/threefoldfoundation/www_ourworld_tf/assets/43240801/8b66a0de-25b9-4131-a9c7-b381b8022a8a)

**Comment by ehab-hassan** [comment]
fixed at production
