### ISSUE TITLE
Bring ourworld.tf to life

### ISSUE THREAD

**Issue by samtaggart** [ourworldventures/www_ourworld_tf#18]
**HOME**
- [x] In the header, check width of subtext, make more narrow if it looks better this way
- [x] Decrease size of lightbulb
- [x] Reduce spacing between What We Provide and the next text, check spacing on whole page
- [x] Make Funding Platform / Technological Platform etc 2x2 instead of 4x1
- [x] Decrease size of the paper airplanes
- [x] Reduce spacing beneath The Foundation of Every Venture
- [x] Reduce space beneath Our Journey

**ABOUT**
- [x] In the header, check the width of the subtext, make more narrow if it looks better this way
- [x] Clean up the rest of the page, make images smaller, etc
- [x] Remove mentions of "$500m" in exits

**VENTURES**
- [x] Add header
- [x] Fix readability of header
- [x] ThreeFold Background is too earthy – change
- [x] Use a different picture for OurVerse
- [x] Add OurPhone since it links to a website

**OTHER**
- [x] Add Blog (sam confirm which)
- [x] Add Newsroom (sam confirm which)
- [x] Add Team (sam confirm who)

**Comment by samtaggart** [comment]
For now:

**BLOG**

- [x] https://www.threefold.io/blog/internet-evolution/
- [x] https://www.threefold.io/blog/tech-as-a-tool-for-humanity/
- [x] https://www.threefold.io/blog/digital-twin/

**NEWSROOM**

- [x] https://www.threefold.io/newsroom/ourworldfreezone/
- [x] https://www.threefold.io/newsroom/africanregensummit/
- [x] https://www.threefold.io/newsroom/zuzalu/

**TEAM**

- [x] Everyone (Please see this issue first)

**Comment by ehab-hassan** [comment]
@samaradel please add blog ,news , people 
- [x] Make sure or external link opens on a new page. 
- [x] fix drop-down menu spaces.

**Comment by samaradel** [comment]
@timurgordon people page not showing [ourworld.tf/people](https://www2.ourworld.tf/people/)

**Comment by samaradel** [comment]
> @timurgordon people page not showing [ourworld.tf/people](https://www2.ourworld.tf/people/)

Fixed, all pages are working now
