### ISSUE TITLE
Broken Knowledgebase links in footer and header

### ISSUE THREAD

**Issue by mik-tf** [ourworldventures/www_ourworld_tf#21]
# Issue

Knowledgebase link is broken (https://ourworldventures.github.io/info_ourworld/intro/intro.html)

![image](https://github.com/ourworldventures/www_ourworld_tf/assets/77026219/f1ebeddc-a930-4366-96f5-8b5daf3b300b)

**Comment by samtaggart** [comment]
Checking to see if we have a public e-book we can link to. The latest version requires name and password.
