### ISSUE TITLE
Update information based on current e-book

### ISSUE THREAD

**Issue by samtaggart** [ourworldventures/www_ourworld_tf#27]
- Keep the website relatively minimal
- Update content to match anything new from the e-book
- Check existing ventures (think we need to add TF9 and change mention of ThreeFold Tech on About page)
- Make sure blog and newsroom are updated
- Longer content from the e-book can be turned into blogs (can backdate some blogs to fill in since last April)
- For news we need to ask Sacha / Florian (maybe we can talk about the roadshow, etc.

Let's propose some recommendations in a document first and get feedback.

e-book link: https://friends.threefold.info/ourworld  (planet/first)

**Comment by emilieo** [comment]
working here on the first draft: https://www.canva.com/design/DAGDgowQMGM/0OGOMkigClrnceVceKVytg/edit?utm_content=DAGDgowQMGM&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
