### ISSUE TITLE
Learn more button not working

### ISSUE THREAD

**Issue by Ashishban** [ourworldventures/www_ourworld_tf#3]
URL - https://ourworld.tf/

Directed to : https://www.ourworld.tf%22/platform%22

<img width="410" alt="3" src="https://user-images.githubusercontent.com/91247662/220096992-1ad355de-6384-4e98-85e8-0ad7d9feec78.png">

<img width="525" alt="2" src="https://user-images.githubusercontent.com/91247662/220097002-3da919db-e9c8-4d8b-ba75-ee8894e4d96a.png">

**Comment by ehab-hassan** [comment]
fixed
