### ISSUE TITLE
Add newsroom item for Transformative Impact Summit

### ISSUE THREAD

**Issue by samtaggart** [ourworldventures/www_ourworld_tf#34]
🇹🇿  **OurWorld @ Transformative Impact Summit**

_“By bringing together those dedicating their lives to making the world a better place, and empowering them with exposure, support, connection, and funding, we not only celebrate transformative impact, we create it.”_

Held this June 7 - 9 in Zanzibar, Tanzania, the [Transformative Impact Summit](https://www.transformativeimpactsummit.com/p/2024) convened with this important focus, attracting an audience of people from around the world working across the entire impact ecosystem, along with students from local IT universities, and government officials from Zanzibar.

A [jam-packed three-day schedule of focused talks](https://www.catalist.network/1-column-agenda/tis-africa-24) gave essential background and context to the incredible group of participants and their initiatives. Different tracks for the summit included Financial Innovation, Regenerative Finance, Regenerative Agriculture and Food, along with health and social connection, and AI, Web3, and Tech for Good.

OurWorld co-founder and CEO Kristof De Spiegeleer spoke several times, once about Public Private Partnerships being a model that can change Africa, once about uplifting Africa with technology, and once about the OurWorld Digital Free Zone.

In addition, ThreeFold ecosystem developer Florian Fournier spoke on the topic of crafting a conscious society for our world on the second day. Gregory Flipo, co-founder of Sikana and ecosystem developer for ThreeFold presented on educational video content on a global scale. And Omrei Abumadi, founder of [VVerse](https://www.vverse.co/) (a ThreeFold & OurWorld collaborator), who discussed the metaverse and showcased a virtual environment built just for the event.

We were grateful for the opportunity to speak about OurWorld and the ecosystem of projects and individuals together collaborating on the path to self-sovereignty.

**Comment by marionrvrn** [comment]
@samtaggart can you please also share a picture

**Comment by marionrvrn** [comment]
committed on branch master_marion @sasha-astiadi

**Comment by sasha-astiadi** [comment]
close for now
