### ISSUE TITLE
Website is very big ... Can we reduce in size?

### ISSUE THREAD

**Issue by samtaggart** [ourworldventures/www_ourworld_tf#37]
Timur mentioned to me that the website is super big.

Actually neither of us can even clone the repo from Zanzibar, this might be a factor.

Should look at ways to reduce the size of the website, maybe through reducing image quality in some places, although I leave it up to the team to decide the best approach.

**Comment by sasha-astiadi** [comment]
hi um i think ill change the layout to astro in general to make it easier for people to edit
