### ISSUE TITLE
Learn more button not working

### ISSUE THREAD

**Issue by Ashishban** [ourworldventures/www_ourworld_tf#6]
URL - https://ourworld.tf/creator-zones/

Directed - https://www.ourworld.tf%22/%22

<img width="416" alt="image" src="https://user-images.githubusercontent.com/91247662/220098977-ebe6ba48-c3a9-48d5-9403-2a8805cc7532.png">

<img width="525" alt="2" src="https://user-images.githubusercontent.com/91247662/220099079-d434d6c5-24bb-4c6c-8628-a72ab3cf05d9.png">

**Comment by ehab-hassan** [comment]
@sasha-astiadi need link here

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldfoundation/www_ourworld_tf/commit/0ecada523c22e71826c268857e04f6530037ce55
