### ISSUE TITLE
Know more button not working

### ISSUE THREAD

**Issue by Ashishban** [ourworldventures/www_ourworld_tf#8]
URL - https://ourworld.tf/platform/

Directed to - https://www.ourworld.tf%22https//threefold.io%22

<img width="461" alt="image" src="https://user-images.githubusercontent.com/91247662/220112133-897290b0-b0ee-4011-8af2-b35696f7edc6.png">

![image](https://user-images.githubusercontent.com/91247662/220112170-abb0171d-4d5e-414b-a4ac-a4dfab11ee8b.png)

**Comment by ehab-hassan** [comment]
@sasha-astiadi what is the link Know More button?

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldfoundation/www_ourworld_tf/commit/9209e642f2ffb39d426de00f0faf651b69ea1653
