### ISSUE TITLE
Same Content used.

### ISSUE THREAD

**Issue by Ashishban** [ourworldventures/www_ourworld_tf#9]
URL - https://ourworld.tf/platform/

Same content is used for Layer 1 and Layer 2

LAYER ONE
THE GRID

Creator Zones are dedicated to building super-sustainable coworking and co-living communities where entrepreneurs, digital nomads and residents collaborate to build beautiful experiences that positively impact the lives of millions.

LAYER TWO
EXPERIENCES

Creator Zones are dedicated to building super-sustainable coworking and co-living communities where entrepreneurs, digital nomads and residents collaborate to build beautiful experiences that positively impact the lives of millions.

**Comment by ehab-hassan** [comment]
@sasha-astiadi please help here

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldfoundation/www_ourworld_tf/commit/3b18ccaeee425b49d80289493170c7eac0ef3f22
